"""empty message

Revision ID: 10581c066b03
Revises: 4802b7470db6
Create Date: 2023-04-05 17:00:21.951704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10581c066b03'
down_revision = '4802b7470db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('valueTtotal',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('cust',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)
        batch_op.alter_column('tax',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=8, scale=2),
               nullable=False)
        batch_op.alter_column('alterResale',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=8, scale=2),
               nullable=False)

    with op.batch_alter_table('service_order', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_order', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('alterResale',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('tax',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('cust',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('valueTtotal',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
