"""empty message

Revision ID: 4802b7470db6
Revises: c40b9126f65d
Create Date: 2023-04-05 16:53:22.219830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4802b7470db6'
down_revision = 'c40b9126f65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('valueResale',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('valueResale',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
