"""empty message

Revision ID: 604f427f4926
Revises: 
Create Date: 2023-03-28 08:59:16.772045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604f427f4926'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prodName', sa.String(length=100), nullable=False),
    sa.Column('valueResale', sa.Float(precision=10), nullable=False),
    sa.Column('cust', sa.Float(precision=10), nullable=False),
    sa.Column('tax', sa.Float(precision=10), nullable=True),
    sa.Column('supplier', sa.String(length=100), nullable=True),
    sa.Column('qt', sa.Integer(), nullable=False),
    sa.Column('alterResale', sa.Float(precision=10), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('genre', sa.Enum('masculino', 'feminino', 'outros', name='genre'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('adresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('zipCode', sa.String(length=9), nullable=False),
    sa.Column('activate', sa.Enum('active', 'inative', name='active'), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adresses')
    op.drop_table('user')
    op.drop_table('products')
    # ### end Alembic commands ###
