"""empty message

Revision ID: 6529e2e1d38d
Revises: 9d0c62bab1bc
Create Date: 2023-04-06 08:50:55.241702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6529e2e1d38d'
down_revision = '9d0c62bab1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('discountTotal',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=2, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('service_order', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_order', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.Numeric(precision=2, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.alter_column('discountTotal',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
