"""empty message

Revision ID: a79675b4c722
Revises: 6529e2e1d38d
Create Date: 2023-04-06 08:53:21.763590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a79675b4c722'
down_revision = '6529e2e1d38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=mysql.DECIMAL(precision=2, scale=2),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=mysql.DECIMAL(precision=2, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
