"""empty message

Revision ID: e11c6c408581
Revises: 90564849672e
Create Date: 2023-04-03 16:39:58.248970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e11c6c408581'
down_revision = '90564849672e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=False))
        batch_op.add_column(sa.Column('street', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('zipCode', sa.String(length=9), nullable=False))
        batch_op.alter_column('complement',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('uf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uf', mysql.VARCHAR(length=2), nullable=False))
        batch_op.alter_column('complement',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('zipCode')
        batch_op.drop_column('street')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
