"""empty message

Revision ID: fb2879a70015
Revises: e11c6c408581
Create Date: 2023-04-03 17:14:56.957709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb2879a70015'
down_revision = 'e11c6c408581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.String(length=18),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=18),
               type_=mysql.VARCHAR(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###
